# =========================================================================
# Script 10B: Ecosystem-Specific Weighting Sensitivity Analysis
#
# Purpose:
#   Evaluate the sensitivity of drought propagation results to reasonable
#   changes in ecosystem-specific RZSM weighting factors.
#
# Input:
#   RZSM outputs generated by Script 10A (Google Earth Engine)
#   NDVI anomaly stack generated by Script 03
#   Ecosystem mask generated for the study
#
# Scenarios:
#   Baseline
#   Forest Deep
#   Forest Shallow
#   Grass Shallow
#   Crop Deep
#
# Processing chain:
#   RZSM
#      ↓
#   3-month aggregation
#      ↓
#   SSMI3
#      ↓
#   Ecosystem spatial averaging
#      ↓
#   Lagged correlation with NDVI anomalies
#      ↓
#   Peak correlation and dominant lag
#
# Study period:
#   2000-2025
#
# Evaluation period:
#   2015-2025
#
# Propagation lags:
#   0-12 months
#
# Output:
#   Table1_Weighting_Sensitivity.csv
#   Table1_Weighting_Sensitivity_Full.csv
#   Weighting_Sensitivity_Lag_Curves.tif
# =========================================================================


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import xarray as xr
import rioxarray as rxr

from scipy.stats import pearsonr


# -------------------------------------------------------------------------
# 1. File names
# -------------------------------------------------------------------------

SCENARIO_FILES = {

    "Baseline":
        "Iran_RZSM_Baseline.tif",

    "Forest Deep":
        "Iran_RZSM_ForestDeep.tif",

    "Forest Shallow":
        "Iran_RZSM_ForestShallow.tif",

    "Grass Shallow":
        "Iran_RZSM_GrassShallow.tif",

    "Crop Deep":
        "Iran_RZSM_CropDeep.tif"
}


NDVI_FILE = (
    "Iran_NDVI_Anom_312months.tif"
)


ECOSYSTEM_MASK_FILE = (
    "Iran_Ecosystem_Mask.tif"
)


# -------------------------------------------------------------------------
# 2. Define timeline
# -------------------------------------------------------------------------

timeline = pd.date_range(
    start="2000-01-01",
    end="2025-12-01",
    freq="MS"
)


print("=" * 75)
print("ECOSYSTEM-SPECIFIC WEIGHTING SENSITIVITY ANALYSIS")
print("=" * 75)

print(
    f"Study period: {timeline[0].strftime('%Y-%m')} "
    f"to {timeline[-1].strftime('%Y-%m')}"
)

print(
    "Evaluation period: 2015-2025"
)

print(
    "Propagation lags: 0-12 months"
)


# -------------------------------------------------------------------------
# 3. Load NDVI anomaly
# -------------------------------------------------------------------------

print("\nLoading NDVI anomaly stack...")


ndvi_stack = rxr.open_rasterio(
    NDVI_FILE
)


if ndvi_stack.sizes["band"] != len(timeline):

    raise ValueError(
        "NDVI anomaly stack does not contain "
        "312 monthly observations."
    )


ndvi_stack = (
    ndvi_stack
    .assign_coords(
        band=timeline
    )
    .rename(
        {"band": "time"}
    )
)


# -------------------------------------------------------------------------
# 4. Load ecosystem mask
# -------------------------------------------------------------------------

print(
    "Loading ecosystem mask..."
)


ecosystem_mask = rxr.open_rasterio(
    ECOSYSTEM_MASK_FILE
).isel(
    band=0
)


# -------------------------------------------------------------------------
# 5. Ecosystem definitions
#
# These IDs must be identical to those used in the GEE workflow.
# -------------------------------------------------------------------------

ECOSYSTEMS = {

    "Forest": 1,

    "Grassland": 3,

    "Cropland": 4
}


# -------------------------------------------------------------------------
# 6. Extract ecosystem-level NDVI anomaly series
# -------------------------------------------------------------------------

def get_ecosystem_series(
    data,
    ecosystem_id
):

    masked_data = data.where(
        ecosystem_mask == ecosystem_id
    )

    series = (
        masked_data
        .mean(
            dim=["y", "x"],
            skipna=True
        )
        .to_pandas()
    )

    return series


print(
    "\nExtracting ecosystem NDVI anomaly series..."
)


ndvi_series = {}


for ecosystem, ecosystem_id in ECOSYSTEMS.items():

    ndvi_series[ecosystem] = (
        get_ecosystem_series(
            ndvi_stack,
            ecosystem_id
        )
    )

    print(
        f"  {ecosystem}: "
        f"{ndvi_series[ecosystem].notna().sum()} "
        f"valid observations"
    )


# -------------------------------------------------------------------------
# 7. Calculate SSMI3
#
# The 3-month RZSM aggregation is calculated first.
# Monthly standardization is then performed separately for each
# calendar month across the complete 2000-2025 period.
# -------------------------------------------------------------------------

def calculate_ssmi3(
    rzsm
):

    # -------------------------------------------------------------
    # 3-month trailing aggregation
    # -------------------------------------------------------------

    rzsm_3m = (
        rzsm
        .rolling(
            time=3,
            center=False,
            min_periods=3
        )
        .mean()
    )


    # -------------------------------------------------------------
    # Calendar-month climatology
    # -------------------------------------------------------------

    monthly_mean = (
        rzsm_3m
        .groupby(
            "time.month"
        )
        .mean(
            "time",
            skipna=True
        )
    )


    monthly_std = (
        rzsm_3m
        .groupby(
            "time.month"
        )
        .std(
            "time",
            skipna=True
        )
    )


    # -------------------------------------------------------------
    # Standardization
    # -------------------------------------------------------------

    ssmi3 = (
        (
            rzsm_3m
            .groupby(
                "time.month"
            )
            -
            monthly_mean
        )
        /
        monthly_std
    )


    ssmi3 = ssmi3.drop_vars(
        "month",
        errors="ignore"
    )


    return ssmi3


# -------------------------------------------------------------------------
# 8. Ecosystem spatial averaging
# -------------------------------------------------------------------------

def spatial_mean(
    data
):

    return (
        data
        .mean(
            dim=["y", "x"],
            skipna=True
        )
        .to_pandas()
    )


# -------------------------------------------------------------------------
# 9. Lagged Pearson correlation
#
# Lag 0:
#   concurrent soil-moisture and vegetation anomalies.
#
# Positive lag:
#   vegetation response follows the preceding soil-moisture anomaly.
# -------------------------------------------------------------------------

def calculate_lagged_correlations(
    forcing,
    response,
    max_lag=12
):

    combined = pd.concat(
        [
            forcing.rename("Forcing"),
            response.rename("Response")
        ],
        axis=1
    ).dropna()


    forcing = combined["Forcing"]

    response = combined["Response"]


    r_values = []


    for lag in range(
        max_lag + 1
    ):

        if lag == 0:

            x = forcing

            y = response

        else:

            x = forcing.iloc[:-lag]

            y = response.iloc[lag:]


        # ---------------------------------------------------------
        # Remove any remaining missing values
        # ---------------------------------------------------------

        valid = (
            np.isfinite(x.values)
            &
            np.isfinite(y.values)
        )


        x = x.values[valid]

        y = y.values[valid]


        # ---------------------------------------------------------
        # Correlation cannot be calculated with too few values
        # ---------------------------------------------------------

        if len(x) < 3:

            r_values.append(
                np.nan
            )

            continue


        if (
            np.std(x) == 0
            or
            np.std(y) == 0
        ):

            r_values.append(
                np.nan
            )

            continue


        r, _ = pearsonr(
            x,
            y
        )


        r_values.append(
            r
        )


    return np.asarray(
        r_values,
        dtype=float
    )


# -------------------------------------------------------------------------
# 10. Process all weighting scenarios
# -------------------------------------------------------------------------

all_results = []

peak_results = []


for scenario, filename in SCENARIO_FILES.items():

    print("\n" + "-" * 75)

    print(
        f"Processing scenario: {scenario}"
    )

    print(
        f"Input: {filename}"
    )

    print("-" * 75)


    # -------------------------------------------------------------
    # Load scenario RZSM
    # -------------------------------------------------------------

    rzsm_stack = rxr.open_rasterio(
        filename
    )


    if rzsm_stack.sizes["band"] != len(timeline):

        raise ValueError(
            f"{filename} does not contain "
            f"312 monthly observations."
        )


    rzsm_stack = (
        rzsm_stack
        .assign_coords(
            band=timeline
        )
        .rename(
            {"band": "time"}
        )
    )


    # -------------------------------------------------------------
    # Calculate SSMI3
    # -------------------------------------------------------------

    print(
        "  Calculating SSMI3..."
    )


    ssmi3 = calculate_ssmi3(
        rzsm_stack
    )


    # -------------------------------------------------------------
    # Evaluate each ecosystem
    # -------------------------------------------------------------

    for ecosystem, ecosystem_id in ECOSYSTEMS.items():

        print(
            f"  Processing {ecosystem}..."
        )


        # ---------------------------------------------------------
        # Spatially averaged SSMI3
        # ---------------------------------------------------------

        ecosystem_ssmi3 = (
            ssmi3.where(
                ecosystem_mask == ecosystem_id
            )
        )


        ssmi3_series = spatial_mean(
            ecosystem_ssmi3
        )


        # ---------------------------------------------------------
        # Restrict to evaluation period
        # ---------------------------------------------------------

        ssmi3_eval = (
            ssmi3_series
            .loc[
                "2015-01-01":
                "2025-12-01"
            ]
        )


        ndvi_eval = (
            ndvi_series[ecosystem]
            .loc[
                "2015-01-01":
                "2025-12-01"
            ]
        )


        # ---------------------------------------------------------
        # Lagged correlation
        # ---------------------------------------------------------

        r_values = (
            calculate_lagged_correlations(
                ssmi3_eval,
                ndvi_eval,
                max_lag=12
            )
        )


        lags = np.arange(
            0,
            13
        )


        # ---------------------------------------------------------
        # Store every lag
        # ---------------------------------------------------------

        for lag, r in zip(
            lags,
            r_values
        ):

            all_results.append(
                {

                    "Scenario":
                        scenario,

                    "Ecosystem":
                        ecosystem,

                    "Lag_months":
                        lag,

                    "Pearson_r":
                        r
                }
            )


        # ---------------------------------------------------------
        # Extract peak
        # ---------------------------------------------------------

        if np.all(
            np.isnan(r_values)
        ):

            peak_r = np.nan

            peak_lag = np.nan

        else:

            peak_index = np.nanargmax(
                r_values
            )

            peak_r = (
                r_values[
                    peak_index
                ]
            )

            peak_lag = (
                lags[
                    peak_index
                ]
            )


        peak_results.append(
            {

                "Scenario":
                    scenario,

                "Ecosystem":
                    ecosystem,

                "Peak_r":
                    peak_r,

                "Dominant_lag_months":
                    peak_lag
            }
        )


        print(
            f"    Peak r = "
            f"{peak_r:.6f}; "
            f"Lag = "
            f"{peak_lag}"
        )


# -------------------------------------------------------------------------
# 11. Convert results to DataFrames
# -------------------------------------------------------------------------

lag_results_df = pd.DataFrame(
    all_results
)


peak_df = pd.DataFrame(
    peak_results
)


# -------------------------------------------------------------------------
# 12. Compare alternative scenarios with baseline
# -------------------------------------------------------------------------

baseline_df = (
    peak_df[
        peak_df["Scenario"] == "Baseline"
    ]
    [
        [
            "Ecosystem",
            "Peak_r",
            "Dominant_lag_months"
        ]
    ]
    .rename(
        columns={

            "Peak_r":
                "Baseline_Peak_r",

            "Dominant_lag_months":
                "Baseline_lag"
        }
    )
)


peak_df = peak_df.merge(
    baseline_df,
    on="Ecosystem",
    how="left"
)


peak_df["Delta_r"] = (
    peak_df["Peak_r"]
    -
    peak_df["Baseline_Peak_r"]
)


peak_df["Absolute_Delta_r"] = (
    peak_df["Delta_r"]
    .abs()
)


peak_df["Lag_change_months"] = (
    peak_df["Dominant_lag_months"]
    -
    peak_df["Baseline_lag"]
)


# -------------------------------------------------------------------------
# 13. Save complete lag-by-lag results
# -------------------------------------------------------------------------

lag_results_df.to_csv(
    "Table1_Weighting_Sensitivity_LagResults.csv",
    index=False
)


# -------------------------------------------------------------------------
# 14. Save peak results
# -------------------------------------------------------------------------

peak_df.to_csv(
    "Table1_Weighting_Sensitivity_Full.csv",
    index=False
)


# -------------------------------------------------------------------------
# 15. Create manuscript-style table
# -------------------------------------------------------------------------

table1 = peak_df[
    [
        "Scenario",
        "Ecosystem",
        "Peak_r",
        "Dominant_lag_months",
        "Delta_r",
        "Lag_change_months"
    ]
].copy()


table1.to_csv(
    "Table1_Weighting_Sensitivity.csv",
    index=False
)


# -------------------------------------------------------------------------
# 16. Calculate maximum sensitivity
# -------------------------------------------------------------------------

alternative_results = peak_df[
    peak_df["Scenario"] != "Baseline"
]


if len(alternative_results) > 0:

    max_delta_index = (
        alternative_results[
            "Absolute_Delta_r"
        ]
        .idxmax()
    )


    max_delta_row = (
        alternative_results
        .loc[
            max_delta_index
        ]
    )


    max_delta = (
        max_delta_row[
            "Absolute_Delta_r"
        ]
    )

else:

    max_delta = np.nan

    max_delta_row = None


# -------------------------------------------------------------------------
# 17. Print final sensitivity summary
# -------------------------------------------------------------------------

print("\n" + "=" * 75)

print(
    "WEIGHTING SENSITIVITY SUMMARY"
)

print("=" * 75)


print(
    table1.to_string(
        index=False
    )
)


print("\n" + "-" * 75)


if max_delta_row is not None:

    print(
        "Maximum absolute change in peak r: "
        f"{max_delta:.6f}"
    )

    print(
        "Scenario: "
        f"{max_delta_row['Scenario']}"
    )

    print(
        "Ecosystem: "
        f"{max_delta_row['Ecosystem']}"
    )

    print(
        "Baseline peak r: "
        f"{max_delta_row['Baseline_Peak_r']:.6f}"
    )

    print(
        "Alternative peak r: "
        f"{max_delta_row['Peak_r']:.6f}"
    )

    print(
        "Lag change: "
        f"{max_delta_row['Lag_change_months']:+.0f} months"
    )


print("=" * 75)


# -------------------------------------------------------------------------
# 18. Create sensitivity curves
# -------------------------------------------------------------------------

fig, axes = plt.subplots(
    1,
    3,
    figsize=(15, 5),
    sharey=True
)


for ax, ecosystem in zip(
    axes,
    ECOSYSTEMS.keys()
):

    ecosystem_results = (
        lag_results_df[
            lag_results_df[
                "Ecosystem"
            ]
            ==
            ecosystem
        ]
    )


    for scenario in SCENARIO_FILES.keys():

        subset = (
            ecosystem_results[
                ecosystem_results[
                    "Scenario"
                ]
                ==
                scenario
            ]
            .sort_values(
                "Lag_months"
            )
        )


        ax.plot(
            subset[
                "Lag_months"
            ],
            subset[
                "Pearson_r"
            ],
            marker="o",
            linewidth=1.8,
            label=scenario
        )


    ax.axhline(
        0,
        linestyle=":",
        linewidth=1
    )


    ax.set_title(
        ecosystem,
        fontsize=12,
        fontweight="bold"
    )


    ax.set_xlabel(
        "Lag (months)"
    )


    ax.set_xticks(
        np.arange(
            0,
            13
        )
    )


    ax.grid(
        alpha=0.25
    )


axes[0].set_ylabel(
    "Correlation coefficient (r)"
)


axes[0].legend(
    fontsize=8
)


fig.suptitle(
    "Sensitivity of Drought Propagation to "
    "Ecosystem-Specific RZSM Weighting",
    fontsize=13,
    fontweight="bold"
)


plt.tight_layout()


plt.savefig(
    "Weighting_Sensitivity_Lag_Curves.tif",
    dpi=600,
    bbox_inches="tight"
)


plt.show()


# -------------------------------------------------------------------------
# 19. Final message
# -------------------------------------------------------------------------

print("\n" + "=" * 75)

print(
    "SCRIPT 10B COMPLETED SUCCESSFULLY"
)

print("=" * 75)

print(
    "Generated files:"
)

print(
    "  - Table1_Weighting_Sensitivity.csv"
)

print(
    "  - Table1_Weighting_Sensitivity_Full.csv"
)

print(
    "  - Table1_Weighting_Sensitivity_LagResults.csv"
)

print(
    "  - Weighting_Sensitivity_Lag_Curves.tif"
)

print("=" * 75)
